- name: Ensure hosts is up and running
  hosts: bitops_servers
  gather_facts: no
  tasks:
  - name: Wait for hosts to come up
    wait_for_connection:
      timeout: 300
  - name: Gather facts
    setup:

- name: Docker Cleanup
  hosts: bitops_servers
  become: true
  tasks:
  - name: Docker Cleanup
    include_tasks: tasks/docker_cleanup.yml