- name: Check if compose files exist
  stat:
    path: "{{ item }}"
  register: file_status
  with_items:
    - "{{ app_install_root }}/{{ app_repo_name }}/docker-compose.yml"
    - "{{ app_install_root }}/{{ app_repo_name }}/docker-compose.yaml"
    - "{{ app_install_root }}/{{ app_repo_name }}/compose.yml"
    - "{{ app_install_root }}/{{ app_repo_name }}/compose.yaml"

- name: Count existing files
  set_fact:
    existing_files: "{{ file_status.results | selectattr('stat.exists') | map(attribute='item') | list }}"

- name: Check the count of existing files
  fail:
    msg: "Can't find a valid compose file. Expected one of: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml. Not running docker-compose up."
  when: existing_files | length < 1

- name: Start docker-compose
  ansible.builtin.command: "docker compose --project-directory {{ app_install_root }}/{{ app_repo_name }} up --detach --build --force-recreate --remove-orphans={{ docker_remove_orphans }}"
  register: output
  async: "{{ ansible_start_docker_timeout }}"
  poll: 5
  when: existing_files | length > 0

- ansible.builtin.debug:
    var: output
