- name: Check if compose files exist
  stat:
    path: "{{ item }}"
  register: file_status
  with_items:
    - "{{ app_install_root }}/{{ app_repo_name }}/docker-compose.yml"
    - "{{ app_install_root }}/{{ app_repo_name }}/docker-compose.yaml"
    - "{{ app_install_root }}/{{ app_repo_name }}/compose.yml"
    - "{{ app_install_root }}/{{ app_repo_name }}/compose.yaml"

- name: Count existing files
  set_fact:
    existing_files: "{{ file_status.results | selectattr('stat.exists') | map(attribute='item') | list }}"

- name: Check the count of existing files
  fail:
    msg: "Can't find a valid compose file. Expected one of: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml. Not running docker-compose up."
  when: existing_files | length < 1

- name: Start docker-compose
  docker_compose:
    project_src: "{{ app_install_root }}/{{ app_repo_name }}"
    restarted: true
    build: yes
    recreate: always
    nocache: yes
    pull: true
  register: output
  when: existing_files | length > 0

- ansible.builtin.debug:
    var: output
