
output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks_master.eks_master_endpoint
}

output "cluster_certificate_authority_data" {
  description = "Endpoint for EKS control plane."
  value       = module.eks_master.cluster_certificate_authority_data
}

output "cluster_auth_token" {
  value     = module.eks_master.cluster_auth_token
  sensitive = true
}

/*
output "kubeconfig" {
  description = "kubectl config as generated by the module."
  value       = module.eks_master.kubectl_config
}


output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks_cluster.config_map_aws_auth
}
*/
