variable "aws_ecs_service_name" {}
variable "aws_ecs_cluster_name" {}
variable "aws_ecs_task_name" {}
variable "aws_ecs_node_count" {}
variable "aws_ecs_app_image" {}
variable "aws_ecs_app_cpu" {}
variable "aws_ecs_app_mem" {}
variable "aws_ecs_security_group_name" {}
variable "aws_ecs_assign_public_ip" {}
variable "aws_ecs_container_port" {}
variable "aws_ecs_lb_port" {}
variable "aws_resource_identifier" {}
variable "aws_resource_identifier_supershort" {}
variable "aws_selected_vpc_id" {}
variable "aws_selected_subnets" {}