variable aws_rds_db_proxy {}
variable aws_aurora_proxy {}
variable aws_db_proxy_name {}
variable aws_db_proxy_database_id {}
variable aws_db_proxy_cluster {}
variable aws_db_proxy_secret_name {}
variable aws_db_proxy_client_password_auth_type {}
variable aws_db_proxy_tls {}
variable aws_db_proxy_security_group_name {}
variable aws_db_proxy_database_security_group_allow {}
variable aws_db_proxy_allowed_security_group {}
variable aws_db_proxy_allow_all_incoming {}
variable aws_db_proxy_cloudwatch_enable {} 
variable aws_db_proxy_cloudwatch_retention_days {}
variable aws_selected_vpc_id {}
variable aws_selected_subnets {}
variable aws_resource_identifier {}
variable aws_resource_identifier_supershort {}
variable incoming_random_string {}
