- name: Check if HOST variable is defined
  shell: "grep '^HOST=' {{ app_install_root }}/{{ app_repo_name }}/.env"
  register: host_variable
  changed_when: false
  failed_when: false

- name: Find the mounted NFS volume
  shell: "grep 'nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=612,retrans=2,noresvport' /etc/fstab | awk '{print $2}'"
  register: nfs_mount_path
  changed_when: false
  failed_when: false
  when: host_variable.stdout == ""
    
- name: Check if efs mount directory is present
  stat:
    path: "{{ nfs_mount_path.stdout }}"
  register: check_efs_mount

- name: Stat test
  debug:
    msg: "The file or directory exists"
  when: check_efs_mount.stat.exists

- name: Unmount the NFS volume
  shell: "umount {{ nfs_mount_path.stdout }} || umount -f {{ nfs_mount_path.stdout }} || umount -fl {{ nfs_mount_path.stdout }}"
  when: host_variable.stdout == "" and nfs_mount_path.stdout != ""

- name: Remove entry from /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: "{{ nfs_mount_path.stdout }}.*'{{ mount_options }}'"
    state: absent
  become: true
  when: host_variable.stdout == "" and nfs_mount_path.stdout != ""
