- name: Check if HOST variable is defined
  shell: "grep '^HOST_DIR=' {{ app_install_root }}/{{ app_repo_name }}/.env"
  register: host_variable
  changed_when: false
  failed_when: false

- name: Find the mounted NFS volume
  shell: "grep 'nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=612,retrans=2,noresvport' /etc/fstab | awk '{print $2}'"
  register: nfs_mount_path
  changed_when: false
  failed_when: false
  when: host_variable.stdout == ""

- name: Unmount the NFS volume
  shell: "timeout 5 umount {{ nfs_mount_path.stdout }} || timeout 5 umount -f {{ nfs_mount_path.stdout }} || timeout 5 umount -fl {{ nfs_mount_path.stdout }}"
  when: host_variable.stdout == "" and nfs_mount_path.stdout != ""

- name: Remove entry from /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: "{{ nfs_mount_path.stdout }}.*'{{ mount_options }}'"
    state: absent
  become: true
  when: host_variable.stdout == "" and nfs_mount_path.stdout != ""
