# copy the repo code to the VM
- name: syncrhonize repo
  ansible.posix.synchronize:
    src: "{{ lookup('ansible.builtin.env', 'BITOPS_OPSREPO_ENVIRONMENT_DIR') }}/app/{{ app_repo_name }}"
    dest: "{{ app_install_root }}"
  register: synchro_repo_output

- ansible.builtin.debug:
    var: synchro_repo_output

- name: copy the .env file
  copy:
    src: "{{ lookup('ansible.builtin.env', 'BITOPS_OPSREPO_ENVIRONMENT_DIR') }}/app.env"
    dest: "{{ app_install_root }}/{{ app_repo_name }}/.env"

- name: merge efs.env if file exists and remove it after
  ansible.builtin.shell: |
    if [ -s {{ app_install_root }}/{{ app_repo_name }}/efs.env ]; then
      {{ app_install_root }}/{{ app_repo_name }}/efs.env >> "{{ app_install_root }}/{{ app_repo_name }}/.env"
      rm {{ app_install_root }}/{{ app_repo_name }}/efs.env
    fi

- name: Install the aws ca bundle
  get_url:
    url: "https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem"
    dest: "{{ app_install_root }}/{{ app_repo_name }}/rds-combined-ca-bundle.pem"
