- hosts: bitops_servers
  become: true
  tasks:
  - name: Wait for it to come up
    include_tasks: tasks/wait_for_connection.yml
  - name: Include install docker
    include_tasks: tasks/install.yml
  - name: Include start
    include_tasks: tasks/start.yml